# Generated by Django 2.2.20 on 2021-12-14 16:56

import cartoview_cms.models.streamfields.Blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0005_auto_20211213_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], label='Header Size')), ('text', wagtail.core.blocks.CharBlock(label='Text', max_length=50))])), ('paragraph', wagtail.core.blocks.RichTextBlock(form_classname='full')), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('list', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(), label='Items'))])), ('accordions', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', max_length=50)), ('content', wagtail.core.blocks.RichTextBlock(label='Content'))])), ('image_text_overlay', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('text', wagtail.core.blocks.CharBlock(label='Text', max_length=200))])), ('image_gallery', wagtail.core.blocks.StructBlock([('image', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Image'))])), ('map', wagtail.core.blocks.StructBlock([('map', cartoview_cms.models.streamfields.Blocks.MapChooserBlock(required=True))])), ('map_catalog', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', max_length=240)), ('featured_maps', wagtail.core.blocks.ListBlock(cartoview_cms.models.streamfields.Blocks.FeaturedMapChooser(), label='Featured Maps'))])), ('separator', cartoview_cms.models.streamfields.Blocks.SeparatorBlock()), ('related_users', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Section title as it appears to the users', label='Title', max_length=200)), ('users', wagtail.core.blocks.ListBlock(cartoview_cms.models.streamfields.Blocks.UserChooserBlock(required=True), label='Users'))])), ('related_module', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Section title as it appears to the users', label='Title', max_length=200)), ('display_size', wagtail.core.blocks.ChoiceBlock(choices=[('1', '1 - Smallest'), ('2', '2'), ('3', '3'), ('4', '4 - Recommended'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12 - Largest')], label='Display Size')), ('pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(page_type=['cartoview_cms.GenericPage']), label='Items'))]))], blank=True),
        ),
    ]
