# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0005_blogpostattacheddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostattacheddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='blogpostattacheddocument',
            name='page',
        ),
        migrations.DeleteModel(
            name='BlogPostAttachedDocument',
        ),
    ]
