# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0036_auto_20190227_1124'),
        ('cartoview_cms', '0006_auto_20190305_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGroup',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.TopicCategory')),
                ('content_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartoview_cms.ContentCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': 'Form with Email'},
        ),
    ]
