# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0007_auto_20190306_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geopage',
            name='content_category',
        ),
    ]
