# Generated by Django 2.2.24 on 2022-05-25 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0007_auto_20211215_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
