# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0009_auto_20190311_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopage',
            name='content_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cartoview_cms.ContentCategory'),
            preserve_default=False,
        ),
    ]
