# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('cartoview_cms', '0012_auto_20190311_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Case Studies Module',
            },
            bases=('wagtailcore.page',),
        ),
    ]
