# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 14:37
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0013_casestudyindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='content_category',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cartoview_cms.ContentCategory'),
        ),
    ]
