# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0019_country_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
