# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0021_organization_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
