# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('cartoview_cms', '0023_newsitem_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
