# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0024_casestudy_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='main_image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='body',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='intro',
        ),
        migrations.AddField(
            model_name='organization',
            name='link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
    ]
