# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('cartoview_cms', '0025_auto_20190313_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basegeopage',
            name='map',
        ),
        migrations.RemoveField(
            model_name='basegeopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='coastalcliffinstability',
            name='app_instance',
        ),
        migrations.RemoveField(
            model_name='coastalcliffinstability',
            name='basegeopage_ptr',
        ),
        migrations.RemoveField(
            model_name='coastalcliffinstability',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coastalerosion',
            name='app_instance',
        ),
        migrations.RemoveField(
            model_name='coastalerosion',
            name='basegeopage_ptr',
        ),
        migrations.RemoveField(
            model_name='coastalerosion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='groundwaterquality',
            name='app_instance',
        ),
        migrations.RemoveField(
            model_name='groundwaterquality',
            name='basegeopage_ptr',
        ),
        migrations.RemoveField(
            model_name='groundwaterquality',
            name='category',
        ),
        migrations.RemoveField(
            model_name='landsubsidence',
            name='app_instance',
        ),
        migrations.RemoveField(
            model_name='landsubsidence',
            name='basegeopage_ptr',
        ),
        migrations.RemoveField(
            model_name='landsubsidence',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mapsnippet',
            name='map_object',
        ),
        migrations.RemoveField(
            model_name='sealevelrise',
            name='app_instance',
        ),
        migrations.RemoveField(
            model_name='sealevelrise',
            name='basegeopage_ptr',
        ),
        migrations.RemoveField(
            model_name='sealevelrise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seawaterintrusion',
            name='app_instance',
        ),
        migrations.RemoveField(
            model_name='seawaterintrusion',
            name='basegeopage_ptr',
        ),
        migrations.RemoveField(
            model_name='seawaterintrusion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='waterpollution',
            name='app_instance',
        ),
        migrations.RemoveField(
            model_name='waterpollution',
            name='basegeopage_ptr',
        ),
        migrations.RemoveField(
            model_name='waterpollution',
            name='category',
        ),
        migrations.DeleteModel(
            name='BaseGeoPage',
        ),
        migrations.DeleteModel(
            name='CoastalCliffInstability',
        ),
        migrations.DeleteModel(
            name='CoastalErosion',
        ),
        migrations.DeleteModel(
            name='GroundWaterQuality',
        ),
        migrations.DeleteModel(
            name='LandSubsidence',
        ),
        migrations.DeleteModel(
            name='MapSnippet',
        ),
        migrations.DeleteModel(
            name='SeaLevelRise',
        ),
        migrations.DeleteModel(
            name='SeaWaterIntrusion',
        ),
        migrations.DeleteModel(
            name='WaterPollution',
        ),
    ]
