# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
        ('cartoview_cms', '0027_auto_20190318_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('abstract', models.CharField(blank=True, max_length=120, null=True)),
                ('body', wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(classname=b'full')), (b'HTML', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'quote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), (b'page_chooser', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'embed', wagtail.wagtailembeds.blocks.EmbedBlock())], blank=True)),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='cartoview_cms.ContentCategory')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MeetingsIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Meetings Module',
            },
            bases=('wagtailcore.page',),
        ),
    ]
