# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0029_traininggalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abstract',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
