# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartoview_cms', '0030_country_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
