# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0031_casestudy_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='main_organization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
