# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 08:50
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0034_geopage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([(b'full_width', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(classname=b'grid-title', max_length=50, required=False)), (b'grid', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'col-sm-12', b'12'), (b'col-sm-11', b'11'), (b'col-sm-10', b'10'), (b'col-sm-9', b'9'), (b'col-sm-8', b'8'), (b'col-sm-7', b'7'), (b'col-sm-6', b'6'), (b'col-sm-5', b'5'), (b'col-sm-4', b'4'), (b'col-sm-3', b'3'), (b'col-sm-2', b'2'), (b'col-sm-1', b'1')], help_text=b'Columns (*/12).', label=b'Number of Columns')), (b'grid_classes', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Classes in the grid', label=b'Classes', max_length=255, required=False)), (b'content', wagtail.wagtailcore.blocks.StreamBlock([(b'text_field', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'content', wagtail.wagtailcore.blocks.RichTextBlock(help_text=b'Type in text field', label=b'Text Field'))]), icon=b'fa-align-justify', template=b'cartoview_cms/streamfields/text_field.html')), (b'list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'bullet_icon', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text=b'Image icon per bullet.', label=b'Image icoon', required=False)), (b'content', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.RichTextBlock(), help_text=b'Content of bullet.', label=b'Bullets'))]), icon=b'list-ul', template=b'cartoview_cms/streamfields/list.html'))], label=b'Inboud Fields'))]), icon=b'fa-th', label=b'Full', template=b'cartoview_cms/streamfields/full_grid.html'))], blank=True, null=True),
        ),
    ]
