# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0037_auto_20190321_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geopagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='geopagegalleryimage',
            name='page',
        ),
        migrations.DeleteModel(
            name='GeoPageGalleryImage',
        ),
    ]
