# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartoview_cms', '0041_auto_20190323_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='related_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_country', to='cartoview_cms.Country'),
        ),
    ]
